### ISSUE TITLE
When do we make this public?

### ISSUE THREAD

**Issue by Explosion-Scratch** [Explosion-Scratch/developed_beta#1]
I'd like to make this public, but I want to add some more branding (make a logo, banner, etc) first. I mainly wanted it private during beta because I was worried someone would steal the idea, or the initial burst of people looking at it would see an incomplete project instead of the current project.

**Comment by ghost** [comment]
You made already

**Comment by retronbv** [comment]
> You made already

he made it public after he made the issue

**Comment by Explosion-Scratch** [comment]
Thanks Mr. Obvious
